import { nanoid } from "nanoid";
export const docLinks: DocLink[] = [
  {
    id: nanoid(),
    title: "Get started",
    link: "/learn",
    hasChildrenLinks: false,
  },
  {
    id: nanoid(),
    title: "User Management",
    link: "/learn/user-management",
    content: `
      \n## User management
      \nManage users and their roles
      \n**Articles**
      \n- [Adding user & assigning location to a user](/learn/user-management/adding-user-assigning-location-to-a-user)
      \n- [Role management](/learn/user-management/role-management)
      \n- [User commission agent](/learn/user-management/role-management)
    `,
    hasChildrenLinks: true,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Adding user & assigning location to a user",
        link: "/learn/user-management/adding-user-assigning-location-to-a-user",
        content: `## Adding Users

        \nTo add a new user:
        \n1. Navigate to User Management -> Users -> Add New.
        \n2. Fill in the user details, select user role, and provide a unique username.
        \n3. Sales Commission Percentage (%): Provide the commission % for this user. This option gets applied if the commission agent feature is enabled.
        \n4. Is Active?: Activate/Deactivate the user.
        \n5. You can edit/delete a user.
        \n6. Assign locations.
        
        \n![Refer to the image below](image_link)
        
        \n**Max Sales Discount:** 
        \nThe maximum discount this user can give during sales in the POS & sales screen. If you don’t want to have this restriction then simply keep this value blank.`,
      },
      {
        id: nanoid(),
        title: "Role management",
        link: "/learn/user-management/role-management",
        content: `## Role Management
          \n## Adding Roles

          \nEvery new business comes with some default roles – Admin & Cashier. Admin has all permissions in the application. Cashier has permission only to the POS section.

          \nYou can create a role by clicking on the Add button -> Giving a role name and then selecting the appropriate permission for that role.

          \nSometimes you may need to give a user access to a/some particular location(s) only. In this case, select the locations from “Access locations” permission. Select “All Locations” to give permission to access all locations for your business.

          \nRoles permissions can be edited & Deleted.

          \n**Note:** You must update the role of an existing user before deleting a role.

        `,
      },
      {
        id: nanoid(),
        title: "User commission agent",
        link: "/learn/user-management/user-commission-agent",
        content: `## Using Commission Agent feature
        \nCommission Agent is useful for many businesses. Businesses pay sales agent/commission agent commission on every sale they bring.

        \n### Enabling & Choosing Commission Agent Type:
        
        \nBy default Commission Agent is Disabled. You can enable it from Settings -> Business Settings -> Sales. Sales Commission Agent drop-down.
        
        \nYou will see 3 different types:
        
        \n- Logged in User: If this option is used then the Logged in User will be automatically considered as the commission agent for the sales added by him. Meaning the user adding the sales will get the commission for the sales.
        
        \n- Select from User’s List: If this option is enabled then in POS & Sales Screen you will see the list of “users” present in your business. The user adding the sales will select the commission agent from the list of users displayed.
        
        \n- Select from Commission Agent List: If this option is enabled then in POS & Sales Screen you will see the list of “Sales Commission Agents” present in your business. The user adding the sales will select the commission agent from the list of “Sales Commission Agents” displayed.
        
        \nSelect the option as per your business requirements.
        
        \n### Adding Commission Percentage:
        
        \nYou can add commission % while adding/editing the User or Sales Commission Agent.
        
        \n### Commission Calculation Type:
        
        \nThe commission for a user can be calculated based on two methods
        
        \n1. **Invoice value:**  With this method, commissions are calculated based on the total invoice amount generated by the agent.
        \n    For instance, if an agent’s monthly invoice amount totals $5000 and the commission percentage is set at 10%, the user will receive $500 as commission.
        
        \n2. **Payment Received:**  Alternatively, commissions can be calculated based on the actual payments received.
        \n    For instance:  if the agent’s monthly invoice amount is $5000 with a 10% commission rate, but only $2000 is received within the month, the user will receive $200 as commission. If the remaining $3000 is received in the following month, the user will receive an additional $300 as commission.
        
        \n### Calculating Commission Amount:
        
        \nTo See the commission amount, Go to Reports -> Sales Representative Report.
        
        \nSelect the User for which you want to see the commission amount.
        
        \nOn selecting it will show you the detailed summary of Total Sale, Total Sale Commission & Total Expense. Also, the table below lists all the transactions.
        
        \n**NOTE:** Sales commission is calculated without shipping or tax. Sales commissions are from the sales of the items, not the overhead cost such as taxes, freight, shipping, handling, etc.
        
        \n### Commission payment:
        
        \nAfter getting the commission amount, Stocksavvy have 2 ways to make payment for the commission.
        
        \nUsing expense
        
        \nCalculate the commission from the sales representative report and after paying the amount add it as an expense in Add Expense menu.
        \nIn Add expense, select the Expense-For dropdown
        `,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Contact Mangement",
    link: "/learn/contact-management",
    hasChildrenLinks: true,
    content: `## Contact Management
    \nManage your suppliers and customers. 
    \n**Articles**
    \n- [Customer & supplier ledger](/learn/contact-management/customer-supplier-ledger)
    \n- [Adding opening balance & payment](/learn/contact-management/opening-balance-and-payment)
    \n- [Contact management(suppliers & customers)](/learn/contact-management/suppliers-and-customers-management)
    \n- [Advanced balance](/learn/contact-management/advanced-balance)
    \n- [Opening balance](/learn/contact-management/opening-balance)
    \n- [Loyalty cards](/learn/contact-management/loyalty-cards)
    \n- [Customer groups](/learn/contact-management/customer-groups)

    `,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Customer & supplier ledger",
        link: "/learn/contact-management/customer-supplier-ledger",
        content: `## To view customer or supplier ledger

        \n1. Go to **Contacts** -> **Supplier/Customer** and click on the **actions** button.
        \n2. In that, you will be able to see Ledger for the customer or supplier.
        \n3. You can select a date-range and use the checkbox filters to show/hide certain transaction types.
        
        \n## Adding Discount for Customer/Supplier on Balance due:
        
        \n- Discount for balance due amount can be added for customer/supplier.
        \n- Click the **add discount** button on the customer/supplier ledger screen.
        \n- On clicking the button, it shows a popup, enter the details and click **save**.
        \n- The discounted amount will be accounted for in their ledger.
        
        \n### NOTES
        
        \n1. **NOTE 1:** This discount can only be added by the admin and not by other users.
        \n2. **NOTE 2:** Also, the Ledger Discount is different from the Sale Discount.
           - While adding a Ledger Discount, it will not be reflected in Sale Discount because the invoice details are not added for the ledger discount. And it is not possible to find to which invoice the discount is added.
        `,
      },
      {
        id: nanoid(),
        title: "Adding opening balance & payment",
        link: "/learn/contact-management/opening-balance-and-payment",
        content: `
        \n## Adding opening balance & payment
        \n## Opening Balance:

        \nOpening balance is the initial balance that a contact (customer or supplier) has at the beginning of using the software.
        
        \n- For customers: It represents the amount the customer has to pay.
        \n- For suppliers: It represents the amount you have to pay to the supplier.
        
        \n### Adding Opening Balance:
        
        \nYou can add an opening balance when adding/editing the supplier or customer. In the add contact screen, you will find the opening balance field.
        
        \n### Viewing Opening Balance Payment:
        
        \nTo view the opening balance of a contact:
        \n1. Go to **List Supplier/customer**.
        \n2. Navigate to the contact's view page.
        \n3. You will find the opening balance & opening balance due.
        
        \n### Pay or Receive Payment of Opening Balance:
        
        \nAdding payment of the opening balance is the same as any other payments:
        \n1. Go to **List Customer/Supplier**.
        \n2. Click on **Actions** -> **Pay**.
        \n3. It will open a popup modal where you can enter the payment amount.
        `,
      },
      {
        id: nanoid(),
        title: "Contact management(suppliers & customers)",
        link: "/learn/contact-management/suppliers-and-customers-management",
        content: `## Adding Suppliers & Customers
        \n1. Go to **Contacts** -> **Suppliers** or **Customer**.
        \n2. Click on **Add New Contact**.
        \n3. Select contact type – Supplier/Customer/Both.
        \n4. Based on the contact type selected, it will show the relevant fields. Fill in the relevant details.
        \n5. Click on **More Information** button to see additional fields.
        \n6. **Pay Terms:** Specify pay term in either days or months to receive notifications of pending payments for suppliers & customers.
        \n7. **Customer Group:** Read details [here](/learn/contact-management/customer-groups).
        \n8. **Credit Limit:** Maximum amount of credit that can be given to the customer. If the credit exceeds this amount in any sales, selling on credit won't be allowed.
        \n9. **Opening Balance:** Initial balance of a customer or supplier before using Stocksavvy. Add any previous balance here.
        \n10. **Advance Balance:** Shows the amount of advance balance paid or taken by the customer/supplier respectively.
        
        \n## Viewing Suppliers & Customers
        \n- To view details about a Supplier or Customer, click on **View** button. It will show complete details along with relevant transactions (Purchases & Sales) for that contact.
        \n- **Pay Due Amount:** Use this button to pay the due amount for a customer or supplier. This will pay the overall due amount for all invoices.
        
        \n## Assigning Contacts to Users
        \n1. In your \`pos\\config\\constants.php\`, change the value of enable_contact_assign to true.
        \n2. When adding the user, check the label “assign to specific contact”.
        \n3. When adding contact, select the user to whom you want to assign.
        
        \n## Changing Default Customer Name
        \n- To change the default customer name from “walk-in-customer” to something else:
          \n1. Go to the database contacts data table.
          \n2. Change the first name field to anything required.
        
        \n## Credit Limit for Customer
        \nCredit limits can be added to customers.
        \nWhen the credit limit is reached, partial or credit sales can't be done for those customers.
        \n- To set the credit limit, go to **Contacts** > **Customers** > **Action** > **Edit** > **More Information** > **Credit Limit**.
        \n- Set this field blank for not having any credit limit for customers.
        \n**NOTE:** Do not set the credit limit as 0 for having no credit limit.
        \n- Credit Limit = 0 (the credit for the customer is 0)
        \n- Credit Limit = blank (no restriction for credit limit (infinite))
        `,
      },
      {
        id: nanoid(),
        title: "Advanced balance",
        link: "/learn/contact-management/advanced-balance",
        content: `## Advanced Balance

        \nAdvanced balance(to customers) is the sum of the amount that the business should pay for the customers.
        \nAdvanced balance(to suppliers) is the sum of the amount that the suppliers should pay for the business.
        
        \nTo add an advanced balance, Go to **Customers -> customers/suppliers** and click on the action button. Here you will find a pay option and click on it.  Add payment pop up will be shown and add the required amount value and click on save button.
        
         
        
           
        \n## Making sales/ purchase using advanced balance:
        
        \nTo make a purchase or sale using this advanced balance, add a sale or purchase. Select the customer/supplier that you have added advanced balance. While making the payment select the advance option and save it.
        `,
      },
      {
        id: nanoid(),
        title: "Opening balance",
        link: "/learn/contact-management/opening-balance",
        content: `## Opening Balance

        \nOpening balance(to customers) is the sum of the amount that the customers have to pay for the business.
        
        \nOpening balance(to suppliers) is the sum of the amount that the business has to pay for the suppliers.
        
        \n### Adding an Opening Balance
        
        \nTo add an opening balance, Go to Contacts->customers/suppliers. Either select the add button or click on edit for an existing user. There you could find a more information button, click on that and add the opening balance amount to be added for that user.
        `,
      },
      {
        id: nanoid(),
        title: "Loyalty cards",
        link: "/learn/contact-management/loyalty-cards",
        content: `## Enabling Reward Points:

        \nBefore diving into Loyalty Cards, make sure you’ve enabled the reward points feature. You can find detailed instructions in our documentation [here](link).
        
        \n## Creating Loyalty Cards for Customers:
        
        \nOnce your reward points are active, follow these straightforward steps to set up Loyalty Cards for your customers:
        
        \n1. Assign a Customer ID: When adding a new customer, make sure to provide them with a unique Customer ID. This ID will serve as their key to unlocking exclusive benefits.
        \n2. Printing the Loyalty Card: Using the assigned Customer ID, print the Loyalty Card. This card is your customer’s ticket to accumulating and redeeming reward points. You need to design & print the card externally (maybe use canva or other designing software to design the card for printing.)
        
        \n## Using Loyalty Cards at the Point of Sale (POS):
        
        \n1. Select Customer: Begin by selecting the customer making the purchase. You can scan the QR/barcode code on their Loyalty Card or enter the customer’s mobile number or enter the customer’s name to associate the sale with their account.
        \n2. Complete the Sale: The system will automatically link the sale to the customer’s Loyalty Card, ensuring they receive the deserved reward points.
        
        \nThat’s it! You’ve successfully integrated Loyalty Cards into your Stocksavvy. Your customers can now enjoy a personalized and rewarding shopping experience.
        `,
      },
      {
        id: nanoid(),
        title: "Customer groups",
        link: "/learn/contact-management/customer-groups",
        content: `## Customer Groups:

        \nWith customer Groups, you can classify a customer as Retail Customers, WholeSale Customer, Friends, Colleagues, and whatever you will love to…
        
        \n1. To add a “Customer Group” go to Contacts -> Customer Groups & Click on “Add” button.
        
        \n2. It will show a popup asking for customer group name & Calculation Percentage. Calculation percentage is used to calculate selling price.
        
        \n### Example:
        
        \n- Suppose if the Selling Price set for a product Product1 is $200
        \n- Customer Group Name = Friend
        \n- Calculation Percentage = -20
        \n- Note: -20 (notice a minus sign) or you may set it 20 = +20%
        
        \n- And you have created a customer with Harry with Customer Group assigned as Friend.
        
        \n- Now go to pos or Sell screen. Select the customer Harry and add the product1.
        
        \n- You will notice that the selling price set for the product1 will be 200-20% = $160
        
        \nThis is how customer Group works.
        
        \nCustomer Group does an internal calculation and applied the calculation percentage to the selling price. It will not show a separate discount on the invoice or the pos screen.
        
        \nThis feature is highly useful when you have retail, wholesale, or different customer categories.
        
        \nYou can view a report for different customer groups from “Customer Groups Report” or in other terms if you have retail and wholesale customer group you can see which type of customer group is giving more sale.
        `,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Products",
    link: "/learn/products",
    hasChildrenLinks: true,
    content: `
    \n## Products
    \nAdd products, categories, and units
    \n**Articles** 
    \n- [Product management](/learn/products/product-management)
    \n- [Import/export products](/learn/products/import-export-products)
    \n- [Delete products (Bulk delete)](/learn/products/delete-products)
    \n- [Variations](/learn/products/variations)
    \n- [Product units](/learn/products/product-units)
    \n- [Product category](/learn/products/product-category)
    \n- [Product stock history](/learn/products/product-stock-history)
    \n- [Product expiry settings](/learn/products/product-expiry-settings)
    \n- [Selling price groups](/learn/products/selling-price-groups)
    \n- [Lot number](/learn/products/lot-number)
    \n- [Product warranty](/learn/products/product-warranty)
    \n- [Duplicate product](/learn/products/duplicate-product)
    \n- [Correcting product stock mis-match or incorrect stock in different reports](/learn/products/product-mismatch-fix)
    \n- [Bulk Edit Products](/learn/products/bulk-edit-products)
    \n- [Opening stock](/learn/products/opening-stock)
    \n- [Enable bulk edit](/learn/products/enable-bulk-edit)
    \n- [Custom labels for products](/learn/products/products-custom-labels)
    `,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Product management",
        link: "/learn/products/product-management",
        content: `
        \n## Adding Products
          \nGo to – Products > Add Products.
          \n- Provide a **Product Name**,
          \n- **Brand**,
          \n- **Units**,
          \n- **Category**
          \n- **Sub-category**
          \n- **SKU**: Add a unique SKU which will be used to identify the product & Print barcode in labels. Leave it empty to auto-generate it. You can also add a Prefix for auto-generated SKU.
          \n- **Barcode Type**: Select a barcode type, default/recommended is C128 option. We recommend changing if only if the product added already have an SKU number for it.
          \n- **Not For Selling**: If a product is marked not-for-selling then it will not be displayed in POS or sales screen. This can be useful when using manufacturing module to make the ingredients as product not-for-selling also if you want to temporary disable selling for some products.
          \n- **Alert Quantity**: Alert quantity is used to alert when remaining stocks reaches to this level or below it.
          \n- **Manage stock**: Enable/Disable stock management at a product level. Product stock management is not required for services like Repairing, Hair Cutting, Web Development Printing. For items with Manage Stock Unchecked (disabled), you can sell them in unlimited quantities.  Selling of service using Stocksavvy
          \n**Business Location**: Select the business location(s) where this product can sold or purchased.
          \nSelect **Applicable tax** for that product. Adding Tax
          \nProduct Type:

          \n### Single Product:

          \nApplicable for products with no variation with them then select single
          \nWhen selecting Single product – You will need to enter the Default product price including/excluding tax, Profit Margin % (you can set default profit margin from settings -> Business Settings; this will help to type % every time). Based on the profit margin it will auto calculate selling price excluding of Tax. You can also enter the selling price manually and it will auto adjust the profit margin for you.

          \n### Variable Product:

          \nApplicable to a product having variations (like size or color or design or flavors etc) You can define variation templates from Products -> Variations. The advantage of creating variation is that it saves time to add same variations multiple time.
          \nWhen selecting Variable product – It will display different fields to add all variations and its related Purchase price, Selling Price. You have to select the variations from the dropdown and it will auto-populate the variations for that template. You can change the variable name, Variation values.
          \n🆕 To give same purchase price or selling price or profit for all variations of a product click on the double tick present in the first variation.
          \nRead more about adding variations

          \n### Combo or Bundle Product

          \nAdding a bundle product

          \nCombo product are also called bundle products.
          \nIt is offering several products as one combined product.
          \nFor example a product “Computer Set” can have: 1 PC Monitor + 1 PC CPU + 1 Pc Keyboard + 1 PC mouse
          \nSo when someone buys Computer set she gets all the products in it.
          \nStock of bundled product depends on stock of individual products present in that bundle.
          \nExample: if you have 5 PC Monitor, 4 PC CPU , 10 pc Keyboard, 50 PC mouse, the stock of Computer set will be 4 PC.
          \nWhen the bundle product is sold, stock of all products inside them is automatically deducted.
          \nIndividual products present in bundle product can also be sold separately.
          \nBundle products cannot be purchased, only individual products present in it can be purchased.
          Click on Save.

          \nYou can edit a product. You can also Copy / Export to CSV, PDF or Excel file.
          ## Adding Products with Multiple Variations:

If you have products which involve multiple variations like for example a Shirt can have Color & Size variation, then we have multiple ways to work with it:

### Solution 1: Create Combined Variation

You can create a variation with a name “Color-Size” and add values like Red-Small, Red-Medium, Red-Large, etc. This can be used while adding the Shirt.

### Solution 2: Create Multiple Products

Create multiple different products like Shirt-Red, Shirt-Green, Shirt-Blue with size as variations. When you create multiple products you will NOT have to enter the same details multiple times, first, add the Shirt-Red with all size variations of it and then use the Duplicate Product action to copy the data.

### Select Required Variations:

While adding variable products, you can select only the required variation values.

In your add/edit product screen, select the product type as ‘variation’ and select the variation name (eg. color).

A dropdown will be displayed, in which you can select the required variation values.

**NOTE:** This option is available only in POS version 5 and above.

### Assigning/Removing Locations of Multiple Products at Once:

Go to List Products and refer to this screenshot.

### Deactivating & Activating Product:

Refer to the screenshot.

### Using Product Barcode:

**Question:**

How can we use the product’s barcode instead of creating and printing new for every product?
How can we use the brand’s barcode of the product instead of creating and printing new for every product?

**Answer:**

When creating a product, in the SKU field enter the barcode number of the product. This barcode will be used to identify the product in all screens like POS, Sales, purchases, reports, and others.

**How to add a product that already has a Barcode?**

Adding products that already have a barcode, follow the same steps as adding any other products.

- Go to add products
- Fill in all the product details
- IMPORTANT: in the SKU field scan or enter the barcode of the product.

### Adding Product Quantity or Adding Product Stock:

For systematically managing your business, product quantities can be added in 3 ways:

- Adding Opening stock
- Adding purchases

        `,
      },
      {
        id: nanoid(),
        title: "Import/export products",
        link: "/learn/products/import-export-products",
        content: `
## Import/Export Products

### Import Products:

#### Steps:

1. Go to Products -> Import Products
2. Download the template file.
3. Fill all the information as per the displayed columns name & instructions. Don’t remove the heading from template file.
4. Import the file

#### Common Errors:

- **Error: UNIT not found**
  - **Solution:** Make sure the unit you provided in excel file is already present in the system. Go to Products -> Units, add the unit & import the file again.

- **Error: The separation symbol could not be found the separation symbol could**
  - **Solution:** Format your cells in excel as text in your excel for the expiry date field and give the date as specified(11-25-2018).

#### Not Well-defined Error:

Many times it can show some not well-defined errors like “non-numeric value encounter” or others

In this case, the best way is to split your import into multiple files.

For example, if you’re importing fil with 500 products, divide it into 2 files of 250 each and import it.

### Export Products:

The products can be exported in excel/pdf formats from the list products screen.

Products can be exported as the same template as the import product template.

In the list products screen, click the download excel button.
        
`,
      },
      {
        id: nanoid(),
        title: "Delete products (Bulk delete)",
        link: "/learn/products/delete-products",
        content: `
## Delete Product (Bulk delete)

### Deleting Products

Deleting of a product will remove the products from the database.

**NOTE:** This delete will not work if the product have some transactions related to it. Transaction can be Opening Stock, Purchase, Sales or Stock transfer of the product. It will show some error like:

- Product can’t be deleted because purchases related to this product exist
- Some products couldn’t be deleted because it has transaction related to it.

### Delete product Errors:

#### Some products couldn’t be deleted because it has transaction related to it:

When a product has any transactions it cannot be deleted.

Transactions can be either Sales, Purchase, or Adding opening stock.

The best way to avoid such products is by deactivation them
        
        `,
      },
      {
        id: nanoid(),
        title: "Variations",
        link: "/learn/products/variations",
        content: `
## Variations

1. Variations can be added from the Products -> Variations menu.
2. These variations are used in variable products product.

Example of variation is, for example, Jeans can have multiple colors, so add variations called Colors and provide the value for it. As given in the image below.

**NOTE:** Delete variation option will not be shown for variations that are already used in some products

## Adding Multiple Variations for Products

If a product has more than one variation, for example, A shirt with size ‘M’ and brand ‘POLO’ or A book with pages 30 and size long.

Add the variation name and type as a combined variation.

Eg: variation name : Size – Pages

variation values  – Long -30, Long -120, Long – 200, Small -30, Small – 120 etc.

        `,
      },
      {
        id: nanoid(),
        title: "Product units",
        link: "/learn/products/product-units",
        content: `
## Adding Units

Go to Products -> Units
Give the unit name, a short name, and choose if want the unit to allow decimals.

Example:
- Name: Meter
- Shortname: Mtr.
- Allow Decimal: Yes.

Allowing decimal allows you to purchase/Sell the product in decimal and vice-versa.
\n## Multiple Units:

This can be useful if you purchase products in a different unit and sell it in a different unit.

For example: Purchase in dozens and sell in pieces.
Or purchase in boxes and sell in pieces.

**Steps:**

1. Add the lower unit from Add Unit Screen. For example pieces.
2. Add the higher unit as per the screenshot:
    - Check “Add as multiple of another unit”
Multiple units - units of measurement
    - Provide the conversion Details.
3. Use the unit in Add/Edit Product. While adding/editing purchase/ sale you can see the dropdown for units. Select the desired unit and it will change the unit purchase/sales price accordingly.

**NOTE:** You will not see the main Units (Dozen in this example) in the Add-Product Unit dropdown, select piece as the unit of product. All purchases/sales get saved in the lower unit (pieces in the above example). So after adding purchases/sales if you edit the conversion details, it will affect the purchases/sales quantity accordingly.
## Selecting relevant Sub Units for a product

For some products not all sub-units will be required. Suppose for example you sell Oranges only in Dozens or only in pieces then it will be useful.

Enable it from Business settings ->Products -> Enable relevant sub-units

Now when adding products select the Unit for the products and it will give option to select multiple applicable sub-units. Selecting the sub-units will allow you to do purchases or sales on this selected sub-units.
## Secondary Units:

Secondary units can be added to products. A secondary unit can be used if a particular product’s subunit may vary each time. For example, 1 piece of stone can be 10 kg or 20 kg, or 30 kg.

To enable this go to Settings-> Business Settings – > Products.

On enabling this, a secondary unit label will be shown in add/edit products screen.

Selecting this product in the purchase/sale/POS screen will also show the secondary unit label.

The details of secondary units for products are shown in the product stock history of that product.

**NOTE:** The secondary unit is not considered for calculation. It is only used for the user’s knowledge of tracking the products with varying subunits.
        `,
      },
      {
        id: nanoid(),
        title: "Product category",
        link: "/learn/products/product-category",
        content: `## Product Category (Categorizing products)

Categorizing products helps you to easily manage and filter them in reports.
        
### Adding Category & Sub-Category
        
Go to Product -> Categories -> Add
Add Category name, category code(HSN code)
If the category is sub-category select “Add as sub taxonomy” and select the parent category.
        `,
      },
      {
        id: nanoid(),
        title: "Product stock history",
        link: "/learn/products/product-stock-history",
        content: `
## Product stock history

- Go to Products > Product List
- Click on Actions > Product stock history

        `,
      },
      {
        id: nanoid(),
        title: "Product expiry settings",
        link: "/learn/products/product-expiry-settings",
        content: `## Product expiry and related settings.

## Enabling expiry for products

1. To enable expiry go to **Settings -> Business Settings -> Product** section. And check the **Enable Product Expiry** checkbox.

2. On enabling Product expiry, you can choose either **Add Item Expiry** or **Add manufacturing date & Expiry Period**

- **Add Item expiry** => Choose this option if you want to directly add the expiry of the item to the purchase screen.
    
- **Add manufacturing date & Expiry date** => Choose this option if you want to add the manufacturing date of the item and the expiry period. Based on the manufacturing date and expiry period it will auto-calculate the expiry date. And this expiry date can be edited. You will have to add expiry period for the product in the “Add or Edit Product” screen. And the manufacturing date in the “Add Purchase” screen.

3. **On Product Expiry** => With this option you can set what the system should do when a product expired.

- **Keep Selling** => Choose this option if you want the application to keep selling the product even after expiry.
    
- **Stop Selling n days before** => Choose this option to stop selling the item n days before the expiry. You will have to specify the value of n (which is the number of days before to stop selling)

4. **Stock Accounting Method** => This feature is used to set the way the product should be sold.

- **FIFO (First In First Out)** => In this the old stock should be sold first.
    
- **LIFO (Last In First Out)** => In this the most recent purchase stock should be sold.

### For an Example:

1. Purchase 20 pcs of product A on 20 March 2018. Expiry date 10 April 2018

2. Purchase 20 pcs of the same product A on 23 March 2018. Expiry date 8 April 2018

3. Today I sold 22 pcs.

If the “Stock Accounting Method” is FIFO => Then the Product purchased on 20 March 2018 will be deduced with 20 pcs and after that product purchase on 23 March 2018 will be deduced with 2 pcs. So in stock, we will have products from 23 March 2018 with 18 pcs.
    
If the “Stock Accounting Method” is LIFO => The opposite of the above will happen.

### Stock Expiry Report:

1. Go to Reports => Stock Expiry Reports.

2. Here you can filter stock “Category”, Brands, “Stock expiry date”

3. Click on “Edit” to modify the stock left and expiry period.

4. If stock left is decreased the unit purchase price is adjusted accordingly.

### Stock Expiry Alert:

- You can view stock expiry alert in Homepage bottom section. Here it shows a list of products expiring soon.

- You can set the number of days before which the expiry alter should be shown in the Homepage from “Settings -> Business Settings -> Dashboard Section” View Stock Expiry Alert For input field.

### Displaying product expiry date in the invoice

- Make sure the product expiry feature is enabled as mentioned above.

- Go to invoice layout and enable “Show Product expiry”

- If the product expiry date is added when adding Purchase or Opening stock then when making sales it will display the product expiry dropdown. Select the expiry date which you want to sell.  Then in the print invoice, it will show the expiry date.
`,
      },
      {
        id: nanoid(),
        title: "Selling price groups",
        link: "/learn/products/selling-price-groups",
        content: `## Selling Price Groups (Sell in different prices: wholesale/retail or for different prices for different locations)
### Adding Selling Price Groups:

1. Go to Products -> Selling Price Group.
2. Click on the “Add” button to add a new price group, such as Retail price, Wholesale price, Location-based price, etc.
3. View the list of selling prices in the “Selling Price Group” screen.

### Adding Selling Price as either Fixed or Percentage:

- Selling price can be added as either fixed or percentage:
- **Fixed:** The value given will be the selling price for that group.
- **Percentage:** The value given will be taken as a percentage of the actual selling price.

### Adding price for different price groups:

1. In the Add/Edit product screen, click on the “Save & Add Selling-price-group price” button.
2. Enter the prices for each selling price group.
3. Click on Save.

### Exporting & Importing selling price group:

1. Go to Products -> Update Price.
2. Download the Excel file by clicking on the “Export Product Prices” button.
3. Update the selling price group prices in the downloaded file.
4. Import the modified file.

### Selling at a particular price group:

1. Go to POS.
2. Select the desired selling price group.
3. The selling prices for the product will be as per the selected price group.

### Assigning a user to a particular price group:

- Create a role with the desired permissions & price group assigned.
- Assign at least one price group for a role if it has permission to sell.

### Assigning a customer to a particular price group:

- Customers can’t be directly assigned to selling price groups.
- Assign the price group to the customer group that has the customer.

### Assigning a price group to a Business Location:

- Helps selling the same product at a different price in different business locations.
- Select the Default Selling Price Group in Add/Edit Business Location.

## FAQ:

**1. How to hide the Selling Price Group in POS window to all cashiers?**
- In add/edit roles, you can set which selling price groups will be visible to that role. 
- In the cashier role, uncheck/remove permission for all other selling price groups except the one intended to be shown or used for the cashier.
        `,
      },
      {
        id: nanoid(),
        title: "Lot number",
        link: "/learn/products/lot-number",
        content: `## Lot Number
## What is Lot Number?

A lot number is a unique identifier assigned to a specific quantity or batch of products produced or processed under identical conditions. It helps in tracking and tracing products throughout their lifecycle, particularly in industries where quality control and product recall are critical.

### Enabling Lot Number

To enable lot number, follow these steps:

1. Go to Settings -> Business Settings -> Purchases.

2. Check the "Enable Lot number" checkbox and update settings.

### Adding Lot number from Purchases

If lot number is enabled, follow these steps to add lot numbers during purchases:

- When adding purchase stock, it will display the lot number field for entering the lot number.

### Adding Lot number from Add Opening Stock

If lot number is enabled, follow these steps to add lot numbers during adding opening stock:

- When adding opening stock, it displays the input field to enter lot number.

### Selling products from specific Lot

Refer to the POS selling documentation Lot number description for guidance on selling products from specific lots.

### Displaying product lot number in the invoice

To display product lot numbers in the invoice, ensure the lot number feature is enabled as mentioned above and follow these steps:

1. Go to invoice layout and enable “Show lot number”.

2. If the lot number is added when adding Purchase or Opening stock, it will display the lot number & product expiry dropdown during sales. Select the lot number which you want to sell.

3. Then in the print invoice, it will show the lot number.

        `,
      },
      {
        id: nanoid(),
        title: "Product warranty",
        link: "/learn/products/product-warranty",
        content: `

## Product Warranty
**Enabling Warranty:**

To enable warrany in products go to Settings -> Business Settings -> Products -> Enable Warranty
## Using Warranty

1. Adding Warranty: Add warranty types by going to Products -> Warranty.
2. Assigining warranty for products: Go to Add/Edit product and select the warranty that is applicable for the product.
3. Sell with warranty: Any products which has warranty assigned when sold will use the transaction date as start of warranty. You can display warranty in receipts by enabling it from Invoice layout.
`,
      },
      {
        id: nanoid(),
        title: "Printing labels",
        link: "/learn/products/printing-labels",
        content: `
## Product labels 
## Customized Label Printing in Stocksavvy

Stocksavvy offers an inbuilt feature to print customized labels for products. You can access the print label screen from multiple places:

1. **From Sidebar Menu:**
   - Go to Products -> Print Labels.

2. **From Product View:**
   - Navigate to Products -> View Products and click on Actions -> Labels to add selected products to the print label list.

3. **From Purchase List:**
   - Visit Purchases -> List Purchases and click on Actions -> Labels to add products from the selected purchase to the print label list.

### Printing Labels:

1. Add the products for which you want to print labels by entering the name or barcode/SKU id.
2. Adjust the quantity of each product's label (No. of labels).
3. Select the information to display in labels by checking/unchecking options under “Information to show in labels” heading.
4. Choose the Barcode Setting according to your sticker. Commonly used settings are included.
   - You can add new settings from Settings -> Barcode Settings menu.
5. Click on Preview to view the labels.
6. If everything looks good, click on Print to print the labels.
   - Note: Set the Margins to ‘default’ in the browser print window.
   - If some information is getting half displayed due to sticker size, consider hiding them or use a 20 Labels Per sheet setting.

### Error Handling:

**Error: Unsupported SKU id for the selected barcode type**

This error indicates that the SKU provided when creating the product doesn’t satisfy the encoding as per the selected barcode type.

**Solution:**
- Edit the product and change the barcode type to “Code 128”, then save & try printing the label again.

        `,
      },
      {
        id: nanoid(),
        title: "Duplicate product",
        link: "/learn/products/duplicate-product",
        content: `
## Duplicate products
Duplicate Products helps you to easily create a new product with the same data as another product, this helps you save repetitive entering of data and ultimately saves time by making the product entry process faster.

**Steps** 
- Right click on the product you want to duplicate 
- Select duplicate products 
- You'll be taken to a page where you can add similar products
        `,
      },
      {
        id: nanoid(),
        title:
          "Correcting product stock mis-match or incorrect stock in different reports",
        link: "/learn/products/product-mismatch-fix",
        content: `
## Correcting Product Stock Mis-Match or Incorrect Stock in Different Reports

### Error 1: Mismatch between sold and purchased quantity

### Error 2: Mismatch in stock shows in Stock-Report and sales screen. 

This discrepancy may occur due to unknown reasons or manual updates to the stock in the database.

### Solution:

**Note:** You must have admin privileges for this procedure.

1. **Navigate to the following URL:** 
   - [www.stocksavvy.io/reports/product-stock-details](www.stocksavvy.io/reports/product-stock-details)

2. **Important:** Select the business location and press the search button. This will display a list of products with mismatched stock.

3. **Important:** Click on the "Fix" button for each product to rectify the discrepancy.

Refer to the screenshot below for further assistance.

      `,
      },
      {
        id: nanoid(),
        title: "Bulk edit products",
        link: "/learn/products/bulk-edit-products",
        content: `
## Bulk Edit Products
Bulk edit helps you to edit multiple products at once and saves your time.

To edit multiple products follow the steps:
        
- Go to Products -> List Products
- Select the products you want to edit by clicking on the checkbox present in each product row.
- Scroll down you will find the Bulk Edit option, click on it and you can edit the selected products.
- Also, in the bulk edit screen you can add any other products to edit them.
`,
      },
      // {
      //   id: nanoid(),
      //   title: "Rack, row & position of product",
      //   link: "/learn/products/rack-row-position-of-product",
      // },
      {
        id: nanoid(),
        title: "Opening stock",
        link: "/learn/products/opening-stock",
        content: `
## Opening Stock
## To add opening stock:

Go to List Products
Actions > Add or Edit Opening Stock
    
## Editing opening stock (or) Making opening stock 0:
    
NOTE: If you have already added an opening stock and have to edit it, follow the steps below.
    
Click the ‘+’ symbol.
A new row will be created
Add the new amount there
    
To make the opening stock to ‘0’, add a negative value in step 3
Eg) If the existing opening stock is 10, add -10 to make the stock quantity to 0 or if you add a negative amount (-4) then the amount will be 6.
`,
      },
      {
        id: nanoid(),
        title: "Enable bulk edit",
        link: "/learn/products/enable-bulk-edit",
        content: `## Bulk Price Update

You can efficiently update the prices of multiple products in bulk using the Bulk Price Update feature.

### Steps:

1. Navigate to **Products > Update Price**.
2. Download the Excel file provided.
3. The Excel file contains a list of product names, SKUs, existing prices of products, and selling group prices (if available).
4. Update the prices of the required products directly in the Excel file.
5. Ensure not to change any product name, SKU, or headers.
6. Upload the modified Excel file.
7. Click submit to apply the changes.

By following these steps, you can quickly and conveniently update the prices of multiple products in bulk.
        `,
      },
      {
        id: nanoid(),
        title: "Custom labels for products",
        link: "/learn/products/products-custom-labels",
        content: `
## Custom labels for products

Custom Labels for Products:

20 custom fields can be added for the product, these custom fields can be used while adding a new product.

Custom fields can be anything related to the product like brand code, product code etc.

To add this Go to **Settings > Business Settings > Custom labels**

Provide the custom label name here.
## Field Type for labels:

The data type can be specified for each custom field. Select text, date picker or dropdown types.

For dropdown add a line break after each option.
        `,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Purchases",
    link: "/learn/purchases",
    hasChildrenLinks: true,
    content: `
\n## Puchases
\n Add purchases, specify the purchase status 
\n**Articles** 
\n- [Purchase management](/learn/purchases/purchase-management)
\n- [Purchase payments](/learn/purchases/purchase-payment)
\n- [Purchase invoice](/learn/purchases/purchase-invoice)
\n- [Purchase requisition](/learn/purchases/purchase-requisition)
\n- [Purchase order](/learn/purchases/purchase-order)
\n- [Adding bonus or free items given by supplier](/learn/purchases/adding-bonus-or-free-items-given-by-supplier)
\n- [Purchase custom fields](/learn/purchases/purchase-custom-fields)

    `,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Purchase management",
        link: "/learn/purchases/purchase-management",
        content: `
## Purchase Management

**Adding Purchase**
1. Go to Purchases -> Add Purchases.
2. Type the Supplier Name or Business name in the Supplier field. If the supplier doesn’t exist, add them from Contacts -> Suppliers -> Add.
3. Enter the Purchase reference number, Purchase date, and Order Status.
4. Select the Business Location: Choose a location where you want to add the purchase. You can add a new Location from Settings -> Business Locations.
5. Type the product name or scan the product barcode number. It will display related matched products; select a product to add it to the purchase list.
6. For each new product, enter the purchase quantity, purchase price, and tax information.
7. To apply a discount: Choose the discount type (fixed or percentage) and enter the amount. UltimatePOS will auto-calculate the discounted amount.
8. Enter purchase tax, Shipping Details, Additional Shipping charges, Payment status, and Additional notes.
9. You can view the list of purchases from Purchases -> List Purchases.
10. To print Labels for your purchase, click “Print Labels” in the List Purchases screen.

## No matching product found Error
**This error may occur due to the following reasons:**
1. There are no products matching the name or SKU entered. Check the product list.
2. Ensure the selected business location in add purchase has the product available.
3. Ensure that Stock Management is enabled for the product in Add/Edit Products.
        
        
`,
      },
      {
        id: nanoid(),
        title: "Purchase payments",
        link: "/learn/purchases/purchase-payment",
        content: `
## Purchase Payments
Purchase payment meaning paying to the supplier for the Purchases

**Payments Statuses**
- **Paid**: The PO is 100% paid.
- **Due**: The PO is 100% not paid.
- **Partial**: Partial amount of the PO has been paid.
- **Overdue**: PO is 100% not paid & past the due date.
- **Partial** Overdue: Partial amount of the PO has been unpaid & past the due date.

**Adding Payments**
1. Adding payment when adding purchase:
   - In the add purchase screen, you can add the payment for the purchase.

2. Adding payment from the List Purchase screen:
   - In list purchase, click the actions for any PO, and it will display the list of actions for it. This option is not displayed if there is no payment due.

3. Adding payments from Contact:
   - Go to contact -> Suppliers. Click on actions for the supplier and it will show “Pay Due amount”, click on it and pay the amount. “Pay Due amount” this option is not displayed if there is no payment due.


`,
      },
      {
        id: nanoid(),
        title: "Purchase invoice",
        link: "/learn/purchases/purchase-invoice",
        content: `
## Purchase Invoice:
An invoice for purchase can be generated at every purchase.

To print a purchase invoice, Go to List Purchase > Actions > Print.

**Barcode for Purchase Invoice:**
The barcode is automatically generated in the purchase invoice based on the purchase invoice number.
        
`,
      },
      {
        id: nanoid(),
        title: "Purchase requisition",
        link: "/learn/purchases/purchase-requisition",
        content: `
## What is Purchase Requisition(PR)
The purchase requisition is a document that an employee creates to request a purchase of some products when the stock reaches a low level.        
Only products less than the alert quantity will be shown while creating the purchase requisition.        
### Enabling Purchase Requisition
1. Go to Settings -> Business Settings -> Purchase and enable the purchase requisition check box.
2. The purchase requisition tab will be shown in the sidebar.
3. Click on add button and provide the required details. Refer to the screenshot below.        
### Converting Purchase Requisition to Purchase Order
Once PR is added it’s converted to Purchase Order.
1. To convert it into a purchase order, follow the steps below.
2. Go to Purchase order -> Add. [Purchase order](/learn/purchases/purchase-order)
3. Here when you select the corresponding supplier the PR id will be shown.
4. Select the required PR id.        
### Partial Purchase
If the ordered quantity in the PR is reduced while converting it into a purchase order, then the status will automatically change from ordered to partial.
        
I hope this format meets your requirements. If you need any further adjustments, feel free to let me know.  
`,
      },
      {
        id: nanoid(),
        title: "Purchase order",
        link: "/learn/purchases/purchase-order",
        content: `
## Purchase Order

## What is a Purchase Order?

A purchase order is a document given by the buyer (usually you) to the supplier to request a purchase of goods.

A purchase order contains the buyer invoicing details, delivery details, products, quantities, pricing, tax, discounts, payment terms, payment details, shipping charges if any, and other notes.

The supplier will issue a sales order against the purchase order you have provided.

A purchase order has multiple statuses: Ordered, Partial, Completed

### Enabling Purchase Order

To enable purchase Order, follow the below steps:

1. Go to Settings -> Business Settings
2. Purchase tab -> Enable Purchase Order
3. Save it.

### Using Purchase Order in UltimatePOS

#### Creating purchase order

After Enabling Purchase order, inside Purchase you’ll find the Purchase -Order menu.

1. Go to add Purchase order, fill in all the details and save it.

2. Stocks are not added on issuing Purchase orders.

3. Once a Purchase order is created you can print it and send it to the supplier.

#### Converting purchase Order to Purchase

On receiving Purchase orders the supplier issues a sales or invoice.

1. Go to Purchase -> Add Purchase, select the supplier.
2. On Selecting it will populate the list of all Purchase orders related to the supplier on the “Purchase Order” dropdown.
3. Select the Purchase Order and it will auto load the products for that order with the product’s price, tax, discounts applied automatically as the sales order.
4. You can increase or decrease the quantity.
5. Save it and the status of the Purchase order will change automatically.


`,
      },
      {
        id: nanoid(),
        title: "Adding bonus or free items given by supplier",
        link: "/learn/purchases/adding-bonus-or-free-items-given-by-supplier",
        content: `
## Adding Bonus or Free Items given by supplier


There are 2 ways you can do this:

### Solution 1:
When adding purchases simply make purchase price 0 for the free items.

### Solution 2:
Find the average price of the item and use that for unit price.

For example, if you purchase 10 quantity for a price of $2 each, 10X2 = $20
and get 2 quantity free, then the average cost of each will become 20/12 = $1.66

`,
      },
      {
        id: nanoid(),
        title: "Purchase custom fields",
        link: "/learn/purchases/purchase-custom-fields",
        content: `
## Purchase custom fields

You can add some custom fields in add/edit purchase & view purchase.
To enable custom fields:

1. Go to settings -> Business settings -> Label for purchase custom fields:
2. Provide a label for the fields you need, fields will automatically get enabled once the label is added.
3. Check “Is required” checkbox to make the field as required in add/edit purchase.
        
        
`,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Stock Adjustment",
    link: "/learn/stock-adjustment",
    hasChildrenLinks: false,
    content: `
\n## What is Stock Adjustment? And how to use it?

\n## Stock Adjustment

\n Stock Adjustment helps you decrease the goods you hold in stock, you can enter manual stock adjustments. It’s generally used to write-off damaged stock, or to adjust quantities after a stock take.

\n To create a stock adjustment

\n1. First, go to “Add Stock Adjustment”
\n2. Select the Business Location & date
\n3. Select Adjustment Type (Normal Or Abnormal). Normal Or Abnormal is generally used to classify adjustment.
\n4. Generally Normal Adjustment meaning: Adjustment for normal reasons like Leakages etc.
\n5. Abnormal meaning: Adjustment for reasons like Fire, Accident etc.
\n6. Add the products & quantity you want to decrease the product.
\n7. **Total amount recovered:** Sometimes you can recover some amount from the damaged stocks, like from insurance claims, selling of scraps etc. If there is no amount recovered then you can simply make it 0. The recovered amount is taken into consideration when making a profit & loss report, it is added to the total profit/loss.

\nThe quantities entered for each product will be deducted from the available quantities.

\nYou can view the details of stock adjustment in “Stock Adjustment Report”.

\nAlso, Stock Adjustment is used in Profit & Loss Report (P & L Report). “Total Stock Adjustment” amount is deducted from (P & L Report) and “Total Stock Recovered” amount is added to Profit & Loss Report.

    `,
  },
  {
    id: nanoid(),
    title: "Stock transfer",
    link: "/learn/stock-transfer",
    hasChildrenLinks: false,
    content: `
## Stock Transfer
Stock transfer is the process of sending or transferring stock from one location to another location within the system.

### Process Overview:

1. **Initiation**: Stock transfer is initiated by selecting the products to transfer and specifying the source (From) and destination (To) locations.
2. **Execution**: The stock is physically moved from the source location to the destination location.
3. **Completion**: The transfer is marked as completed in the system, indicating that the stock has been successfully transferred.
4. **Stock Adjustment**: The stock level decreases from the source location and increases in the destination location upon completion of the transfer.

### Key Points:

- Stock transfers only affect stock levels when the status is marked as "Completed."
- Changes in stock levels do not occur for transfers with statuses such as "Pending" or "In-Transit."
- Once a transfer is marked as completed, it cannot be edited but can be deleted if necessary.
- Editing a stock transfer is only possible when the status is either "Pending" or "In-Transit."
- If stock does not appear in the destination location after a transfer, ensure that the product is added to that location and that the transfer status is marked as completed.

By following these steps and considering these key points, you can effectively manage stock transfers between different locations within the system.
    
`,
  },
  {
    id: nanoid(),
    title: "Sales / sell",
    link: "/learn/sales",
    hasChildrenLinks: true,
    content: `
\n ## Sales 
\n Make sales, add sales order, sell services and do more using Stocksavvy
\n **Articles** 
\n - [Sales order](/learn/sales/sales-order)
\n - [Selling Pos Screen](/learn/sales/selling-pos)
\n - [Tender change or change return](/learn/sales/tender-change-change-return)
\n - [Featured products in pos](/learn/sales/featured-products)
\n - [Selling services](/learn/sales/selling-services)
\n - [Sales return](/learn/sales/sales-return)
\n - [Sales subscriptions](/learn/sales/sales-subscriptions)
\n - [Cash register](/learn/sales/cash-register)
\n - [Invoice layout](/learn/sales/invoice-layout)
\n - [Displaying QR code in invoice](/learn/sales/displaying-qb-code-in-invoice)
\n - [Gift receipt](/learn/sales/gift-receipt)
\n - [Inovice url](/learn/sales/invoice-url)
\n - [Keyboard shortcut for pos screen](/learn/sales/keyboard-shortcut-for-pos-screen)
\n - [Discounts by brand, category, and location](/learn/sales/discounts)
\n - [Reward and loyal points](/learn/sales/reward-points)
\n - [Types of service](/learn/sales/types-of-service)
\n - [Shipments, Home delivery or parcel management](/learn/sales/shipments-home-delivery-parcel-management)
\n - [Display product unit price in POS product suggestion](/learn/sales/display-product-unit-price-in-pos-product-suggestion)
\n - [Cash denomination](/learn/sales/cash-denomination)
\n - [Proforma invoice](/learn/sales/proforma-invoice)
\n - [Adding bonus or free items at sale](/learn/sales/adding-bonus-or-free-items-on-sale)
    `,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Sales order",
        link: "/learn/sales/sales-order",
        content: `## Sales order
A Sales Order is a document provided by a supplier to a buyer in response to a Purchase Order issued by the buyer. It contains detailed information about the products, quantities, pricing, taxes, discounts, payment terms, shipping charges, and other relevant details agreed upon between the buyer and the supplier.

### Key Components of a Sales Order:

- **Buyer Details**: Invoicing and delivery details of the buyer.
- **Product Information**: Description, quantity, pricing, tax, and discounts for each product ordered.
- **Payment Terms**: Terms agreed upon for payment.
- **Shipping Details**: Information regarding shipping charges and delivery.
- **Notes**: Any additional information or special instructions.

### Sales Order Status:

- **Ordered**: Initial status when the sales order is created.
- **Partial**: When only a portion of the order has been fulfilled.
- **Completed**: When the entire order has been fulfilled.

### Enabling Sales Order:

To enable Sales Order functionality:

1. Go to Settings -> Business Settings.
2. Navigate to the Sales tab.
3. Enable Sales Order and save the settings.

### Using Sales Order in Stocksavvy:

#### Creating a Sales Order:

1. Access the Sales Order menu after enabling the feature.
2. Add a new sales order and fill in all the required details.
3. Save the sales order.

#### Converting Sales Order to Sales:

1. Navigate to Sales -> Add Sales.
2. Select the business location and customer.
3. Choose the relevant sales order from the dropdown menu.
4. The products from the selected sales order will be automatically populated.
5. Adjust quantities if necessary and proceed with the sale.

By utilizing the Sales Order feature, businesses can efficiently manage and track orders from creation to fulfillment, ensuring smooth transactions with customers.
        

`,
      },
      {
        id: nanoid(),
        title: "Selling Pos Screen",
        link: "/learn/sales/selling-pos",
        content: `
### Selling Products, Changing Product Price, Tax & Discount, Lot Number & Expiry

**Go to** – Sell -> POS

**Selecting Customer:**
- By default, there is “Walk-In Customer”. You can search for a customer by name/customer ID or phone number or can add a new customer by clicking the plus (+) button “Add Customer”.

**Searching & Adding Product:**
- Enter Product Name Or scan the barcode to search for the product. If multiple products are matched then it displays the dropdown of products, selects the product from it. Or if there is a single product then it directly gets added to cart.

**Changing Product Price, Tax & Discount for a Product:**
- After the products get added, click on the product name to modify the product price, tax & discounts.
- *Note*: Option for different tax in products will be shown only if Inline tax is enabled. You can enable it from Business Settings -> Tax -> Enable Inline Tax in purchase and sell.

**Selecting Lot Number for a Product:**
- If lot number tracking is enabled then it will show the option to select a lot number. (Enabling Lot number)

**Selecting Expiry for a Product:**
- *Expiry Date*: If the expiry date is enabled then it will show the option to select a lot number. (Enabling expiry)

**Cancel Sales:**
- To cancel the sales click on the cancel button. Cancel invoices are not saved in the system, so no stock will be deducted.

**To finalize the invoice click on Finalize** – Add the payment options and save it.
- On save, it will display an invoice printing option.
- *Note*: For the invoice to print correctly – The Margins options should be set to “Default”.

**List of sales** can be viewed from Sell -> List Sales.
**List of drafts** can be viewed from Sell -> Drafts.
Both Sell & Drafts can be edited to make any changes.

**Express Checkout:**
- Express Checkout means the sale will be marked as Paid, and the payment method will be cash. No separate payment screen will be displayed. Printing of the invoice depends on the business location settings.

**100% Credit Sales:**
- To sell on credit to the customer you first need to enable this button by going to Settings -> Business Settings -> POS -> Show Credit Sale Button
- Then on the POS screen, you will be able to see a button “Credit Sale”, simply click this button to make sales on credit.

**Half Credit & Half Payment Sales:**
- Suppose invoice amount is $1000, customers pay $700 cash and $300 is a credit amount on him, then follow these steps:
  1. Click on the multiple pay button
  2. Select the payment method and enter the amount paid by the customer. ($700 in our example)
  3. Click finalize payment.
  4. Now, the pending amount is automatically added as a credit amount on him (or the amount to be taken from the customer)

**Previous Sale Amount in Sales:**
- If a sale is made for the customer for a subsequent time for the same product, the previous amount in which the product is sold will be shown for reference in the add sale screen.

This feature can also be used for purchase of the same products from a supplier.
*Note*: This feature is available in version 4.7.8 and above

**Draft & Quotation:**
- This is useful if you want to create a quotation before sales.
- Marking a sale as Draft or Quotations will not deduct the available stock.
- You can view all Quotations & Drafts from List Quotation or List Draft respectively. Existing draft/Quotation can be edited to make it as final sales.

### Convert Draft/Quotation to Sale Invoice

To convert a draft/quotation to a sale invoice, follow the steps below:

1. Go to **List Draft** / **List Quotation**.
2. Click on the action button.
3. Select **edit** in the dropdown.
4. Change the status from draft/Quotation to Final and save it.

### Copy Quotation

Quotations can be copied or duplicated.

1. Go to **Sale** > **List Quotations** > **Actions** > **Copy Quotation**.

### Suspended Sales

Suspend Sales means an unfinished sale or hold Sale. Suspended sales stock gets deducted from available stock. You can view all suspended sales by clicking on the Yellow Color button present in the very top right of the screen (above the date).

#### Some Use Case of Suspended sales

- In a grocery store, if you have a suspended button, you can suspend particular customers' sales and entertain another customer. When they come back, you can proceed with their sale.
- In a Restaurant, you can suspend the order of customers if not yet paid, and finish it when they finish eating and pay their order, so you can proceed to final sales. You can use identifiers like Table 1, Table 2, Table 3... so when they finish, it’s easy to identify which table is going to pay.
- In a hotel, lots of customers check-in, stay for 2 nights and order some food. Customers might say, just charge it to room 024. So you can suspend their orders and edit if there are additional orders and suspend again until they pay their bills. In the hotel, the Reference Number could be Room 009, Room 012.

### Card / Multiple Pay / Cash

- **Multiple Pay**: Used when the customer wants to pay with different payment methods like some amount by card, some by cash, and some other payment methods. This option is also used when the customer doesn’t pay the exact tender amount and you need to calculate the Return Change.
- **Card**: Used when the customer wants to pay the complete invoice by card.
- **Cash**: Used when the customer pays the exact amount of the invoice by cash. If the customer pays less or more amount then the invoice amount then use Multiple Pay to get change return.

### Adding Payments from Contact

- Go to **contact** -> **Suppliers**. Click on actions for the supplier, and it will show “Pay Due amount”, click on it and pay the amount. “Pay Due amount” this option is not displayed if there is no payment due.

### Adding/Editing Payment Method or Pay-Via

- Follow Add/Edit Pay-Via / payment method.

### Rounding Mechanism for Total Sales Amount or Total Payable

Rounding helps to round the total payable to the nearest currency exchange available.

- To enable rounding go to Settings -> Business Settings -> Sales and choose the Amount rounding method

#### Amount Rounding Method

- **Round to Nearest Whole Number**: It will round the payable value to the nearest whole number. For example, 1.49 will be rounded to 1.00, and 1.51 will be rounded to 2.00.
- **Round to Nearest Decimal (Multiple of 0.05)**: It will round the payable value to the nearest decimal number which is a multiple of 0.05. For example, 1.49 will be rounded to 1.50, 1.51 will be rounded to 1.50, 1.59 will be rounded to 1.60, 1.54 will be rounded to 1.55. Similarly, all other round to nearest decimal numbers work as per the multiplier.

`,
      },
      {
        id: nanoid(),
        title: "Tender change or change return",
        link: "/learn/sales/tender-change-change-return",
        content: `
### Tender Change or Change Return

Suppose during POS the total payment amount by a customer is $250, but the customer pays $300 cash.

In this case, the cashier needs to return $50 cash to the customer.

So, enter all these details in the system, follow the below steps:

1. Click on the “Multiple Pay” button. It will open a popup.
2. Enter the paid amount by the customer ($300 here).
3. On the right side, it will show a “Change Return” Amount. This amount needs to be returned to the customer.
4. Click on finalize button to save the sales.

The change amount is shown in the invoice. To create a custom label for change return, follow these steps:

1. Go to Settings -> Invoice layout.
2. Change the ‘change return label’ to a required label.
3. Save the changes.

        `,
      },
      {
        id: nanoid(),
        title: "Featured products in pos",
        link: "/learn/sales/featured-products",
        content: `
### Featured Products for POS Screen

Adding featured products helps you quickly access some products which are frequently or most commonly sold.

To add featured products, follow these steps:

1. Go to **Settings -> Business Locations**.
2. Add/Edit any business location.
3. In the add/edit screen, you can select multiple products that can be featured in POS for this location.
4. Select featured products in the add/edit business location.
`,
      },
      {
        id: nanoid(),
        title: "Selling services",
        link: "/learn/sales/selling-services",
        content: `
### Using Stocksavvy for Selling of Services

Stocksavvy can be utilized for:

- Exclusively for Services
- Exclusively for Product Selling (trading)
- Combination of Services & selling of Products

#### Selling Services

Services are intangible products, examples include repairing, salon & spa services, web development, consulting, plumbing, etc.

1. **To add a service:**
   - Go to **Add New Products**.
   - Add the name of your service, such as Computer Repair, Accounting, E-Commerce Development, Consulting, Plumber, etc.
   - Uncheck the “Manage Stock?” option. Services typically do not have a stock count associated with them.
   - If you want to add a description for the service, enable the “Enable Product description, IMEI or Serial Number” checkbox.

2. **Creating an invoice or receipt for a service:**
   - Go to **Add Sales** or **POS** screen.
   - Enter the name of the service.
   - If you have enabled “Enable Product description, IMEI or Serial Number”, a popup will appear to add a description. If not, you can click on the button provided.
   - To print the description on the invoice, go to **Settings -> Invoice Settings -> Invoice Layout**. Select the layout you’re using, enable “Show sale description”, and click on “Update”.

Now the description you entered will be displayed on the invoice or receipt.

`,
      },
      {
        id: nanoid(),
        title: "Sales return",
        link: "/learn/sales/sales-return",
        content: `
## Adding Sales Return in Stocksavvy

There are two ways to add sales returns in Stocksavvy

### First Way:
1. Edit existing invoice for the sales by going to edit the invoice.
2. Remove the product or reduce the quantity of the product.
3. Save the changes.
4. The system will automatically add the returned quantity back to stock. This is a simple & recommended way of doing returns.

### Second Way:
Follow the steps in the screenshot provided.

**Question:** Why does the sales return value not decrease the payment value from the parent invoice?

Stocksavvy will adjust these values in the Profit & Loss report. Regarding payment, users have to add a transaction for receiving payment from the customer and then paying them back. This way, all the transactions are recorded.

`,
      },
      {
        id: nanoid(),
        title: "Sales subscriptions",
        link: "/learn/sales/sales-subscriptions",
        content: `
## Sales Subscriptions
**Enabling Subscriptions:**

To enable subscription, go to \`Modules\` -> Check the “Enable Subscriptions” and save it.

**IMPORTANT:** For subscription invoice to auto-generate, a cron job must be set up.

## Using Subscriptions:

Subscriptions can be added from both POS sales or normal Sales screen.
In POS or sales screen to add a subscriptions click on “Subscribe?” Checkbox

On clicking subscribe it shows a popup modal, enter the subscription frequency like every 1 day or every 5 days or every 1 month etc. Also enter the subscription frequency, like if a user wants so subscribe only 5 times the enter 5, for unlimited leave it blank.

All subscriptions appear in Sell -> Subscriptions screen. From here you can also start/stop a subscription.
When a subscription invoice is auto-generated then a notification is sent to admin & sales person.

## Subscriptions Indicators:

While adding subscription sales, the sales will be marked with an indication in the “All Sales” screen.

This indicator will be in either of two colors, blue or red.

The indicators represent:

1. The blue color indicates that this is an automatically created subscription invoice.
2. The red color indicates that it is a recurring invoice that repeats for a specified number of times and turns to the blue color invoice when the number of times specified is reached.
`,
      },
      {
        id: nanoid(),
        title: "Cash register",
        link: "/learn/sales/cash-register",
        content: `
## Cash Register Overview
The Cash Register provides an overview of a particular user/cashier session.

- When a cashier opens the POS screen, they must Open the Cash Register by entering the “Cash In hand”.
- If the cashier has access to more than one location, they also need to select the location
- Every sale made by the cashier will be logged into the Cash Register. 
- In the POS screen, you can view the Register details by clicking on the “Register details” button present in the top navigation bar. It displays the Cash in hand and details of cash transactions by other payment methods, as well as the amount refunded by the cashier.
- To close a cash register, click on the Red Color – Close Register Button. When closing the Cash register, the cashier will have to enter the details of the Total Cash, Total Card Slips, Total Cheques, and other fields.
- To view all cash registers, go to Reports -> Register Report. Here you can view all cash register details.
        
`,
      },
      {
        id: nanoid(),
        title: "Invoice layout",
        link: "/learn/sales/invoice-layout",
        content: `
## Invoice Layout

Invoice Layout allows you to create different invoice formats tailored to your needs.

### Adding a New Invoice Layout:

1. Navigate to Settings -> Invoice Settings -> Invoice Layout -> Add.
2. Provide a unique and distinguishable Layout name.
3. Add the text to be shown in the top/header of the invoice. Typically, this includes your shop name, aligned center with Heading 1 format.
4. Include other relevant details as needed.
5. Choose to show/hide address fields.
6. Optionally, mark a layout as default. The default layout is used when no layout is found for a location.
7. Click on Save.

### Assigning an Invoice Layout to a Location:

1. Go to Business Locations -> Edit.
2. Assign the desired invoice layout to the location.

### Invoice Design:

In the invoice layout settings, you will find options for invoice designs.
- These designs are used for browser-based printing only and NOT for print server-based printing.
- The slim design is particularly suitable for thermal line printer-based printers.
## Tax Summary

To view the tax summary in the invoice, follow these steps:
1. Go to add/edit invoice layout.
2. Enter the "Tax Summary Label" option.
3. The tax summary will now be displayed in the invoice.

## Total in Words

To display the total in words in the invoice, enable the following:
- Show total in words
- Choose "Word Format"

## Discounted Price

To display the discounted unit price and discount amount in the invoice, enable the following fields in the invoice layout:
- Discounted unit price label
- Discount label

## Display Unit Breakdown

To display the reduction summary of quantity from multiple units, enable the checkbox "Show base unit details (If applicable)".

## Adding Sale Custom Fields in the Invoice

1. Go to Settings > Invoice Settings > Invoice Layout.
2. Select the desired invoice layout.
3. Enable the checkboxes for the sale custom fields, such as "sell 1", "sell 2", etc.
4. Save the changes.

Now, the custom fields set up for sales will appear on the printed invoice when using this chosen invoice layout.

## Letterhead

You can add a letterhead image containing all details of your business to invoices:
1. Go to Settings > Invoice Settings > Invoice Layout.
2. Enable the "Show Letterhead" checkbox.
3. Upload the letterhead file (Max 1 MB).

The letterhead will be displayed at the top portion of the invoices.

`,
      },
      {
        id: nanoid(),
        title: "Displaying QR code in invoice",
        link: "/learn/sales/displaying-qb-code-in-invoice",
        content: `
## Displaying QR Code in Invoice
To display a QR code in an invoice, follow these steps:

1. Edit an invoice layout.
2. Scroll down to the QR code section at the bottom.
3. Click on "Show QR Code".
4. Enable all the fields required in the QR code, such as Business Name, Invoice URL, and others.
5. Save the invoice layout.
6. Print an invoice, and you'll see the QR code in the invoice.

### Additional Options:

- **Show Labels:** Enable this option to show the labels (key-value pair) in the QR code.
- **ZATCA (Fatoora) QR code:** This is mostly required in Saudi Arabia. Enabling this will generate a QR code in LTV-base64 format.
        
`,
      },
      {
        id: nanoid(),
        title: "Gift receipt",
        link: "/learn/sales/gift-receipt",
        content: `
## Gift Receipt

To print a gift receipt, follow these steps:

1. **Add a New Invoice Layout**:
- Create a new invoice layout with the name "Gift Receipt".

2. **Set Invoice Design**:
- In the invoice layout settings, select the "Slim" option for the Invoice Design.
- Check the "Hide all prices" checkbox.

3. **Update POS Settings**:
- Go to \`Business Settings -> POS\`.
- Check the "Show invoice layout" dropdown and save the settings.

Now, whenever you want to issue a gift receipt in the POS screen, simply select the "Gift Receipt" invoice layout and print the invoice.
`,
      },
      {
        id: nanoid(),
        title: "Inovice url",
        link: "/learn/sales/invoice-url",
        content: `
## Invoice External URL

1. With invoice external URL you can share the invoice to a customer via a link.
2. With this link, they can see & print the invoice without having to log into the system.
3. The link can also be sent in Email & SMS notification. To send the URL in Email/SMS notification, add it in the notification template using the URL tag.

        
`,
      },
      {
        id: nanoid(),
        title: "Keyboard shortcut for pos screen",
        link: "/learn/sales/keyboard-shortcut-for-pos-screen",
        content: `
## Configuring keyboard shortcuts for POS screen

Stocksavvy supports keyboard shortcuts, by default we have configured shortcuts for different actions in the POS screen.

But you can configure it yourself as per your convenience.

To configure keyboard shortcuts, go to Settings -> System Settings. Here in the POS section, you will find a list of Operations and the shortcuts for them.

You can use the Available Key Names with any combination of letters or numbers to create shortcuts.

- Make sure the shortcuts do not conflict (are not the same) with the shortcuts of the browser. Making a shortcut the same as the browser will have different effects in different browsers.
        `,
      },
      {
        id: nanoid(),
        title: "Discounts by brand, category, and location",
        link: "/learn/sales/discounts",
        content: `
## Discounts by Brand, Category, Location
## Add/Edit Discount:
- **Name**: Enter a meaningful name for the discount.
- **Brand**: Select the product brand where it will be applied.
- **Category**: Select the product category where it will be applied.
- **Location**: Select the location.
- **Priority**: Discounts with higher priority will have higher weight, but priority will not be considered for exact matches. For example, if there are 2 discounts available for the same brand and/or category, then the discount with higher priority will be applied.
- **Discount type**: Fixed or Percentage.
- **Start At**: Start date of the discount.
- **End At**: End date of the discount.
- **Apply in selling price groups**: If checked, then the discount will be applied in the selling price group price. If not, then it will not be applied.
- **Apply in customer groups**: If checked, then the discount will be applied in the customer group price. If not, then it will not be applied.
- **Is active**: Activate or not.
        
`,
      },
      {
        id: nanoid(),
        title: "Reward and loyal points",
        link: "/learn/sales/reward-points",
        content: ` 
## Reward Points, Royalty points

**Enabling Reward Points:**
1. Go to Settings -> Business Settings -> Reward Points Settings.
2. Click on Enable Reward Point to enable it.

Reward Points Settings:

**Earning Points Settings:**
- Reward points display name: This is the display or label name for reward points.
- Amount spent for unit point: The amount the customer needs to spend to earn one reward point. For example, if set to 10, every $10 spent earns one reward point.
- Minimum order total to earn a reward: The minimum amount the customer must spend to earn reward points.
- Maximum points per order: The maximum reward points a customer can earn in one invoice.

**Redeem Points Settings:**
- Redeem amount per unit point: The value of each point when redeemed. For example, if 1 point is $1, enter 1; if 2 points are $1, enter 0.50.
- Minimum order total to redeem point: The minimum order total for customers to redeem points.
- Minimum redeem point per order: The minimum points that can be redeemed per invoice.
- Maximum redeem point per order: The maximum points that can be redeemed in one order.
- Redeem point expiry period: The expiry period for earned points. Expired points are deducted automatically after this period. Set in months or years.

NOTE: Ensure the cron job is set for the expiry feature to work. [Cron Job Document](link)

To display customers' remaining reward points in the invoice, select the option in the invoice layout.

`,
      },
      {
        id: nanoid(),
        title: "Types of service",
        link: "/learn/sales/types-of-service",
        content: `
## Types of Service:
1. **Enabling Types of Service:**
- Go to Settings -> Business Settings -> Modules.
- Check the "Types of Service" option and save it.

2. **Adding New Types of Service:**
- Navigate to Settings -> Types of Service -> Add.
- Provide a name and description.
- Select the Price Group applicable for each location. Choose the Default Selling price if selling at the default price.
- Enter packing charges, if applicable. Leave empty if not applicable.
- Enable custom fields to add additional information in the POS screen.

3. **Using Type of Service in POS/Sales Screen:**
- With Types of Service enabled in the POS screen, you will see the option to select the type of service.
- Before adding a sale, select the type of service and enter relevant details.

4. **Displaying Type of Service Information in Receipt:**
- Enable the option to display type of service information in the receipt from Invoice Layout.

`,
      },
      {
        id: nanoid(),
        title: "Shipments, Home delivery or parcel management",
        link: "/learn/sales/shipments-home-delivery-parcel-management",
        content: `
## Shipments, Home Delivery or parcel management

**Adding a Delivery Person Option for Shipments:**
1. While adding shipment details during a sale, the delivery person can also be added.

**NOTE:** This feature is available in UltimatePOS version 5.2 and above.

**Adding Delivery Note for Sale:**
\nTo add a delivery note, follow these steps:

Step 1: Ensure to include shipping details while adding the sales.
Step 2: Navigate to the All Sales screen and locate the specific sale.
Step 3: Click on the Action dropdown menu for the sale.
Step 4: Select the 'Delivery Note' option from the dropdown menu.
Step 5: Proceed to print the delivery note directly.

`,
      },
      {
        id: nanoid(),
        title: "Display product unit price in POS product suggestion",
        link: "/learn/sales/display-product-unit-price-in-pos-product-suggestion",
        content: `
## Display product unit price in POS Product suggestion
To display product unit price in POS product suggestion follow the below steps:
Go to Business Settings > POS > Enable “Show pricing on product suggestion tooltip”

and save it.

Then in POS screen Product suggestion tooltip, it will show the product unit price
`,
      },
      {
        id: nanoid(),
        title: "Cash denomination",
        link: "/learn/sales/cash-denomination",
        content: `
## Cash Denomination

**What is Cash Denomination?**
Cash denominations refer to the different cash tender used in your country. With this feature, cashiers can easily calculate the total amount they have when closing the register by specifying the number of different tendered notes and coins they possess.

Enabling Cash Denomination:
1. Go to Business Settings -> Settings.
2. Navigate to the POS tab.
3. In the Cash Denomination field, enter the comma-separated cash denominations you would like to have.

**Using Cash Denomination:**
- When a cashier closes the cash register, they will be prompted to enter the count of each cash denomination.
- Upon entering, the total amount will be automatically calculated.

This count can be viewed from the Report -> Cash Register report by viewing any register.

**Cash Denomination in Sale and Purchase:**
- Cash denominations can be added while making a sale or purchase.
- To enable this, go to Settings -> Payment.
- Select the screens in which you need the cash denomination and type of payment method.

The cash denomination table will be shown while making a sale or purchase in the add sale/add purchase screen.


`,
      },
      {
        id: nanoid(),
        title: "Proforma invoice",
        link: "/learn/sales/proforma-invoice",
        content: `
## Proforma Invoice
A proforma invoice is an estimated invoice that is used to request payment from the buyer for goods or services before they are supplied.

The quotations can be converted to proforma invoices.

- Select *Convert to proforma invoice* from the action dropdown button on the list quotation page.

The proforma invoices will be added to the **list drafts** screen. You can convert them later into actual invoices.
`,
      },
      {
        id: nanoid(),
        title: "Adding bonus or free items at sale",
        link: "/learn/sales/adding-bonus-or-free-items-on-sale",
        content: `
## Adding Bonus or Free Items at Sale

Adding Bonus or Free Items at Sale:
Follow the steps below to add a free item during a sale.

Add free items(that have an actual purchase price) during the sale by making the selling price 0 for those products.
Include a note in the sale description indicating that these items are free, bonus, or complementary products.
Enable the ‘sale description’ check box in the invoice layout to ensure that it is printed on the invoice (if required).
        `,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Tax setting",
    link: "/learn/tax-setting",
    hasChildrenLinks: true,
    content: `
\n## Tax Setting 
\nEnable taxes on Stocksavvy
\n**Articles**
\n - [Tax rates, tax groups & disabling tax](/learn/tax-setting/tax-rates-tax-groups-disabling-tax)
`,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Tax rates, tax groups & disabling tax",
        link: "/learn/tax-setting/tax-rates-tax-groups-disabling-tax",
        content: `
## Tax Rates, Tax Groups & Disabling tax

**Tax Rates**

- To add new tax go to Settings -> Tax Rates -> Add
- Add a descriptive name (eg: “VAT@5%”) and specify the “Tax Rate%”

**Tax Groups**

1. Sometime you will need to apply multiple taxes to an invoice or purchase. So you should create tax groups by combining multiple taxes.
2. To add a Tax Group – Click on Add Button, Give a meaningful name, select the tax you want to use in this tax group.
3. The tax rate of tax group will be the sum of tax rates of Sub-taxes added.
4. If sub-tax is edited the corresponding tax group’s tax rate will also get updated accordingly.
5. You cannot delete a Tax if it is used in a Tax Group.

**Disable Tax**

1. Don’t add Tax Rates in settings
2. Go to Settings – Business Settings.
    1. Uncheck **Enable inline tax in purchase and sell**
    2. Uncheck **Enable Price & Tax info**
    3. Select **Default Sale Tax** as None
`,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Payment accounts",
    link: "/learn/payment-accounts",
    hasChildrenLinks: true,
    content: `
\n ## Payment accounts 
\n Enable payment accounts and use payment accounts on Stocksavvy
\n **Articles**
\n - [Enabling & using Payment account or bank account](/learn/payment-accounts/enabling-using-payment-account-or-bank-account)
\n - [Setting default payment accounts for payment methods](/learn/payment-accounts/setting-default-payment-accounts-for-payment-methods)

    `,
    childrenLinks: [
      {
        id: nanoid(),
        title: "Enabling & using Payment account or bank account",
        link: "/learn/payment-accounts/enabling-using-payment-account-or-bank-account",
        content: `
\n ## Enabling & using Payment account or bank account
\n **What is payment accounts in Stocksavvy?**

\nPayment accounts are like for example bank account. You can transfer money from one payment account to another, deposit cash in payment account, pay to a supplier, or deposit the amount received from a customer here.
Enabling Payment account

\n - Go to **Settings ->Business Settings -> Modules**
\n - Enable payment ‘Account’ option
\n - Save it.
\n - After saving you will see the “Payment accounts” option will be visible in the left navigation bar.

\n ## Payment account type & sub-type

\n 1. Go to **Payment accounts -> List accounts -> Account Types**
\n 2. **Account type:** to add an account type click on Add button and enter the name of the account type and submit. Keep the Parent account type unselected.
\n 3. **Sub-Account type:** To add a sub-account type click on Add button, enter the name of the sub-account type and select the Parent-account-type.
\n 4. When creating an account you can select the account type as per your need.

\n ## Creating Payment accounts

\n 1. To create a payment account, Go to Payment Accounts -> List Accounts, click on Add button
\n 2. Fill in all the details like name, account number, Account type, opening balance, Account details & notes.
\n 3. **Account Details:** Here you can add any additional account details, like for example UPI ID, SWIFT code, BIN number, etc which vary depending on the accounts.

\n ## Transferring funds between Payment accounts:

You can transfer funds between the payment accounts.

In the Payment Accounts -> List Accounts, click on fund transfer.
        `,
      },
      {
        id: nanoid(),
        title: "Setting default payment accounts for payment methods",
        link: "/learn/payment-accounts/setting-default-payment-accounts-for-payment-methods",
        content: `
\n ## Setting default payment accounts for payment methods

\n In Add/Edit business location you can select the default payment account for each payment method.

\n If the payment account is linked then when adding a payment for sales/purchase/expense, on selecting the payment method the payment account will be automatically selected.`,
      },
    ],
  },
  {
    id: nanoid(),
    title: "Reports",
    link: "/learn/reports",
    hasChildrenLinks: false,
    content: `
\n ## Reports 
\n Reports help you to get an overview of your entire business
\n To view report click on Reports & Select the report you want to view.

\n Some Reports come filter relevant options to help you analyze your business better.
\n ## Purchase & Sale Report

\n This report shows the total purchase, Purchase Including tax, Purchases with Dues amount; and Total Sale, Sale Including tax, Sale Due.
\n ## Tax Reports

\n Shows the Input & Output Taxes.
\n ## Contacts Report(Customers & Suppliers Reports)

\n This report shows the details of Purchase & Sell with all contacts (Suppliers & Customers) and also any Due amount. Positive Due amount indicates payment by contact, negative indicates payments to the contact.
\n ## Stock Report

\n The stock report displays the stock details. With this, you can track the remaining stock and total sold quantity sold for all products.

\n **For variable products** – you can click on the Green Plus button before the SKU column to get details stock reports for each product variations.
\n ### Stock value by Purchase & sales price

\n In the stock report, you can also get information about the current stock value based on their purchase price & value based on selling price. Check the below screenshot of stock report.

\n ## Tracking product stock report with date

\n To check the product stock report datewise, use the **‘product stock history‘** link in the stock report.

\n ## Trending Products Report

\n - This report helps you to determine the demand of the products.
\n - You can apply different filters to filter the product.
\n - Select a Business Location to view trends for a particular business location.
\n - Select Product Category, Sub-Category, Brands, Units, Date Range to filter them.
\n - Set “No. of products” to view the top that amount of product. Using this you can view Top 5, Top10 or any number of top products.

\n ## Expense Report

\n Expense report helps you to analyze expenses for business locations and also analyze based on expenses categories.
\n ## Register Report

\n View details of all registers and filter registers based on User and/or Status (Open or Closed)
\n ## Sales Representative Report

\n - View Sales and Expenses details of Sales representative
\n - Filter them with User, Business Location, Date Range

\n ## Grouping Invoices in Product Sell Report

\n Invoices are grouped based on certain criteria in the product sell report for the user’s convenience.

\n Go to **Reports > Product Sell Report** and click the Grouped tab.

The criteria used for grouping invoices here are date and product name.
    
For example; All Butter Cookies sold today will be shown in one row, and Butter Cookies sold yesterday will be shown in another row. Similarly for each product the invoices are grouped based on date and product.
    `,
  },
];
