export const timezones = [
  [
    {
      id: 1,
      name: "HOLY FAMILY HOSPITAL",
      currency_id: 87,
      start_date: "2023-05-22",
      tax_number_1: null,
      tax_label_1: null,
      tax_number_2: null,
      tax_label_2: null,
      code_label_1: null,
      code_1: null,
      code_label_2: null,
      code_2: null,
      default_sales_tax: null,
      default_profit_percent: 25,
      owner_id: 1,
      time_zone: "Africa/Lagos",
      fy_start_month: 1,
      accounting_method: "fifo",
      default_sales_discount: "0.00",
      sell_price_tax: "includes",
      logo: null,
      sku_prefix: null,
      enable_product_expiry: 0,
      expiry_type: "add_expiry",
      on_product_expiry: "keep_selling",
      stop_selling_before: 0,
      enable_tooltip: 1,
      purchase_in_diff_currency: 0,
      purchase_currency_id: null,
      p_exchange_rate: "1.000",
      transaction_edit_days: 30,
      stock_expiry_alert_days: 30,
      keyboard_shortcuts:
        '{"pos":{"express_checkout":"shift+e","pay_n_ckeckout":"shift+p","draft":"shift+d","cancel":"shift+c","recent_product_quantity":"f2","weighing_scale":null,"edit_discount":"shift+i","edit_order_tax":"shift+t","add_payment_row":"shift+r","finalize_payment":"shift+f","add_new_product":"f4"}}',
      pos_settings:
        '{"amount_rounding_method":null,"cmmsn_calculation_type":"invoice_value","razor_pay_key_id":null,"razor_pay_key_secret":null,"stripe_public_key":null,"stripe_secret_key":null,"cash_denominations":null,"enable_cash_denomination_on":"pos_screen","enable_cash_denomination_for_payment_methods":["cash","custom_pay_1"],"disable_pay_checkout":0,"disable_draft":0,"disable_express_checkout":0,"hide_product_suggestion":0,"hide_recent_trans":0,"disable_discount":0,"disable_order_tax":0,"is_pos_subtotal_editable":0}',
      weighing_scale_setting:
        '{"label_prefix":null,"product_sku_length":"4","qty_length":"3","qty_length_decimal":"2"}',
      enable_brand: 1,
      enable_category: 1,
      enable_sub_category: 1,
      enable_price_tax: 1,
      enable_purchase_status: 1,
      enable_lot_number: 0,
      default_unit: null,
      enable_sub_units: 0,
      enable_racks: 0,
      enable_row: 0,
      enable_position: 0,
      enable_editing_product_from_purchase: 1,
      sales_cmsn_agnt: null,
      item_addition_method: 1,
      enable_inline_tax: 0,
      currency_symbol_placement: "before",
      enabled_modules:
        '["purchases","add_sale","pos_sale","stock_transfers","stock_adjustment","expenses","account","subscription"]',
      date_format: "m/d/Y",
      time_format: "24",
      currency_precision: 2,
      quantity_precision: 2,
      ref_no_prefixes:
        '{"purchase":"PO","purchase_return":null,"purchase_requisition":null,"purchase_order":null,"stock_transfer":"ST","stock_adjustment":"SA","sell_return":"CN","expense":"EP","contacts":"CO","purchase_payment":"PP","sell_payment":"SP","expense_payment":null,"business_location":"BL","username":null,"subscription":null,"draft":null,"sales_order":null}',
      theme_color: null,
      created_by: null,
      enable_rp: 0,
      rp_name: null,
      amount_for_unit_rp: "1.0000",
      min_order_total_for_rp: "1.0000",
      max_rp_per_order: null,
      redeem_amount_per_unit_rp: "1.0000",
      min_order_total_for_redeem: "1.0000",
      min_redeem_point: null,
      max_redeem_point: null,
      rp_expiry_period: null,
      rp_expiry_type: "year",
      email_settings:
        '{"mail_driver":"smtp","mail_host":null,"mail_port":null,"mail_username":null,"mail_password":null,"mail_encryption":null,"mail_from_address":null,"mail_from_name":null}',
      sms_settings:
        '{"sms_service":"other","nexmo_key":null,"nexmo_secret":null,"nexmo_from":null,"twilio_sid":null,"twilio_token":null,"twilio_from":null,"url":null,"send_to_param_name":"to","msg_param_name":"text","request_method":"post","header_1":null,"header_val_1":null,"header_2":null,"header_val_2":null,"header_3":null,"header_val_3":null,"param_1":null,"param_val_1":null,"param_2":null,"param_val_2":null,"param_3":null,"param_val_3":null,"param_4":null,"param_val_4":null,"param_5":null,"param_val_5":null,"param_6":null,"param_val_6":null,"param_7":null,"param_val_7":null,"param_8":null,"param_val_8":null,"param_9":null,"param_val_9":null,"param_10":null,"param_val_10":null}',
      custom_labels:
        '{"payments":{"custom_pay_1":"Moniepoint","custom_pay_2":"Access Bank","custom_pay_3":null,"custom_pay_4":null,"custom_pay_5":null,"custom_pay_6":null,"custom_pay_7":null},"contact":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null,"custom_field_5":null,"custom_field_6":null,"custom_field_7":null,"custom_field_8":null,"custom_field_9":null,"custom_field_10":null},"product":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null},"location":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null},"user":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null},"purchase":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null},"purchase_shipping":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null,"custom_field_5":null},"sell":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null},"shipping":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null,"custom_field_5":null},"types_of_service":{"custom_field_1":null,"custom_field_2":null,"custom_field_3":null,"custom_field_4":null,"custom_field_5":null,"custom_field_6":null}}',
      common_settings:
        '{"default_credit_limit":null,"default_datatable_page_entries":"25"}',
      is_active: 1,
      created_at: "2023-05-22 18:38:28",
      updated_at: "2023-10-04 16:38:25",
    },
  ],
];
